name: Code Quality

on:
  push:
  pull_request:

jobs:
  quality:
    name: Quality Gate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .
      # - name: Unit & Integration tests
      #   run: pnpm test
      # - name: Smoke & Acceptance tests
      #   run: |
      #     pnpm build-storybook --quiet
      #     pnpm playwright install
      #     npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
      #       "npx http-server storybook-static --port 6006 --silent" \
      #       "npx wait-on tcp:127.0.0.1:6006 && yarn test-storybook"
